name: Manual2 Workflow
on:
  workflow_dispatch:
    inputs:
        titleCustom:
            description: Type test
            type: string
            required: true
            default: "Hello world"
    
jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Even vars
            run: |
              echo "Title ${{ inputs.titleCustom }}" 
    


              