name: scheduler Workflow
on:
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Even vars
            run: |
              echo $GITHUB_SHA
              echo $GITHUB_REF


              


