name: First Workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Display node version on Ubuntu
            run: node -v
    run-second-command:
        runs-on: windows-latest
        steps:
          - name: Display node version on Windows
            run: node -v
    run-third-command:
        runs-on: macos-latest
        needs: run-second-command
        steps:
          - name: Display node version on MacOs
            run: node -v


