name: Manual workflow
on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'      # Поле будет выводиться в форме ручного запуска
          required: true                # если это поле обязательно
          default: 'warning'            # можно установить значение по умолчанию

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Log level is ${{ github.event.inputs.logLevel }}"
  ssh_run:  
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH
        env:
          SSH_HOST: ${{ secrets.STAGE_SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          echo $SSH_HOST
          ssh -i private_key.pem -o StrictHostKeyChecking=no hafizov@$SSH_HOST <<EOF
            mkdir -p /home/hafizov/123
          EOF