name: Manual workflow
on:
  workflow_dispatch:


jobs:
    run-ssh-command:
        runs-on: ubuntu-latest
        steps:
          - name: ssh_check
            env:
              SSH_HOST: ${{ secrets.STAGE_SSH_HOST }}
              SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            run: |
              echo "$SSH_PRIVATE_KEY" > private_key.pem
              chmod 600 private_key.pem
              echo $SSH_HOST
              