name: Manual workflow
on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'      # Поле будет выводиться в форме ручного запуска
          required: true                # если это поле обязательно
          default: 'warning'            # можно установить значение по умолчанию

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Log level is ${{ github.event.inputs.logLevel }}"