name: Test Env
on:
    workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
#      - name:
#        run: |
#          echo ${GITHUB_SHA}
#          echo ${GITHUB_SHA::7}
#          BRANCH=$(echo ${GITHUB_SHA::7}
#          echo $BRANCH
#          echo $GITHUB_REF
#          BRANCH1=$(echo ${GITHUB_REF#refs/heads/})
#          echo $BRANCH1
      - name: Check Vars
        run: |
          echo "MY_VARS: ${{ vars.TEST_VARS }}"

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_ANOTHER_KEY: ${{ secrets.USERNAME }}

      - name: Check Vars
        run: |
            ls -la
            cat .env


