name: manual Workflow
on:
  workflow_dispatch
    
jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
          - name: Even vars
            run: |
              echo $GITHUB_SHA
              echo $GITHUB_REF


              


