name: Third Workflow
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
          - name: List Files and Copy Repo
            run: |
              pwd
              ls -la
          - uses: actions/checkout@v4
          - name: List files
            run: ls -a
              

